### ISSUE TITLE
Prevent people from gaming the bot when sending direct messages

### ISSUE THREAD

**Issue by miketheman** [jimmycuadra/lita-karma#21]
Not sure if this can be done, but we have a user who figured out that they can directly message the bot "in secret" and game the karma system.

I _think_ it would be a change in https://github.com/jimmycuadra/lita-karma/blob/master/lib/lita/handlers/karma/chat.rb#L95-L127 - but I don't know that there's a semantic of `restrict_to` for direct messages, or something like that.

**Comment by jimmycuadra** [comment]
Do you mean you only want it to respond to karma messages in a group chat room?

**Comment by miketheman** [comment]
@jimmycuadra Yes, that's a succinct way of putting it.

**Comment by jimmycuadra** [comment]
Lita 5 will make this type of thing much easier because it will allow you to restrict routes to group chat rooms (see jimmycuadra/lita#145) and override properties of routes in handlers from the configuration file (see jimmycuadra/lita#100). In light of these upcoming changes, I don't want to change lita-karma's code for this use case right now, though I quite like the idea!

**Comment by miketheman** [comment]
That's great news! And agreed - not likely to be worthwhile changing the code now, I've told off the user and warned with a "manual setting of -1000 directly in the db".

**Comment by jimmycuadra** [comment]
Haha, karma is serious business! :D

**Comment by miketheman** [comment]
Closing, as I don't use lita any more
